import {Component, Input, OnInit, ViewChild} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {ActivatedRoute, Router} from "@angular/router";
import {ApiAction, CmsCommonService, JsonApiService, NotificationService, UserService, ValidationService} from "@app/core/services";
import {I18nService} from "@app/shared/i18n/i18n.service";
import {Title} from "@angular/platform-browser";
import {MomentPipe} from "@app/shared/pipes/moment.pipe";
import {BrdCateCd, DataTablePageRequest, DataTablePageResponse, GameRst, GameSetDayRst, GameSetWeekRst, User, UserDetails} from "@app/model/commomModels";
import {Brd} from "@app/model/commomModels";
import {DatatableComponent} from "@app/shared/ui/datatable/datatable.component";
import {Moment} from "smartadmin-plugins/bower_components/moment/moment";
import {timer} from "rxjs";
import {ParticipantModalComponent} from "@app/features/clinical/participant/modal/participant-modal.component";
import {ConformityDetailsModalComponent} from "@app/features/clinical/participant/details/conformity/details-modal/conformity-details-modal.component";

declare let $: any;
declare let moment: any;
// interface Dictionary<T> {
//     [key: string]: T;
// }
// interface Where {
//     fromDate: Date;
//     toDate: Date;
// }

@Component({
    selector: 'app-participant-history',
    templateUrl: './participant-history.component.html',
    styleUrls: ['./participant-history.component.css'],
    providers: [CmsCommonService]
})


export class ParticipantHistoryComponent implements OnInit {
    @ViewChild(ConformityDetailsModalComponent) modal: ConformityDetailsModalComponent;
    @ViewChild(DatatableComponent) table: DatatableComponent;
    @Input() user: User;
    private startDt: Date;
    private endDt: Date;
    private i18n: I18nService;

    constructor(private route: ActivatedRoute, private cmsCommonService: CmsCommonService, public router: Router, private jsonApiService: JsonApiService, public userService: UserService, private validationService: ValidationService) {
        this.i18n = I18nService.getInstance();
        this.i18n. subscribe(() => {
            if(this.table)
                this.table.draw()
        });
    }

    ngOnInit() {
        console.log(this.user);
        // this.selectStartDate(this.user.ptcpStDt);
        // this.selectEndDate(this.user.ptcpEndDt);
        // this.selectDate(new Date());
        // this.where = {fromDate: this.cmsCommonService.getMondayOfWeek(), toDate: this.cmsCommonService.getSundayOfWeek()};
        // this.betweenDate = this.cmsCommonService.betweenDates(this.where.fromDate, this.where.toDate, 'days', 1);
        // timer(5000).subscribe(it => this.table.render());
    }

    options = {
        // autoRender: false,
        serverSide: true,
        paging: true,
        ordering: false,
        lengthMenu: [[50, 100, 150, -1], [50, 100, 150, "All"]],
        buttons: [
            {
                extend: 'excelHtml5',
                text: I18nService.getInstance().getTranslation('Excel'),
                title: 'clinical-participant-history',
                // exportOptions: {
                //     title: 'vvvv',
                //     modifier: {
                //         page: 'current'
                //     }
                // }
            }
        ],
        // buttons: [
        //     'copy', 'csv', 'excel', 'pdf', 'print'
        // ],
        // oTableTools: {
        //     "aButtons": [
        //         "copy",
        //         "csv",
        //         "xls",
        //         {
        //             "sExtends": "pdf",
        //             "sTitle": "SmartAdmin_PDF",
        //             "sPdfMessage": "SmartAdmin PDF Export",
        //             "sPdfSize": "letter"
        //         },
        //         {
        //             "sExtends": "print",
        //             "sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
        //         }
        //     ],
        //     "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
        // },
        ajax: (data, callback, setting) => {
            let where = {"size": data.length, "page": data.start / data.length, "draw": data.draw} as DataTablePageRequest;
            if(this.startDt) {
                where['startDt'] = moment(this.startDt).toISOString();
            }
            if(this.startDt) {
                where['endDt'] = moment(this.endDt).toISOString();
            }
            const action = new ApiAction<DataTablePageResponse<GameSetWeekRst>>(this.router.url+"/history");
            action.param = where;
            action.success = (data: DataTablePageResponse<GameSetWeekRst>) => {
                if (data.data && data.data.length) {
                    data.data.forEach(it => {
                        it.startDt = moment(it.startDt).toDate();
                        it.endDt = moment(it.endDt).toDate();
                    });
                }
                callback(data);
                // this.options['page']()
                // let dataTable2 = this.table.getDataTable();
                // console.log(dataTable2.page.info());
            }
            this.jsonApiService.get(action);
        },
        columns: [
            {data: 'rstSeq', className: 'text-center col-md-1', defaultContent: ""},
            {data: 'dt', className: 'text-center ', defaultContent: "",
                render: (data, display, row: GameRst) => {
                    // return moment(row.msmtStDt).format('YYYY.MM.DD HH:mm:ss') + ' ~ ' + moment(row.msmtStDt).format('YYYY.MM.DD HH:mm:ss');
                    return moment(row.msmtStDt).format('YYYY.MM.DD');
                }
            },
            {data: 'msmtStDt', className: 'text-center ', defaultContent: "",
                render: (data, display, row: GameRst) => {
                    // return moment(row.msmtStDt).format('YYYY.MM.DD HH:mm:ss') + ' ~ ' + moment(row.msmtStDt).format('YYYY.MM.DD HH:mm:ss');
                    return moment(data).format('HH:mm:ss');
                }
            },
            {data: 'msmtEndDt', className: 'text-center ', defaultContent: "",
                render: (data, display, row: GameRst) => {
                    // return moment(row.msmtStDt).format('YYYY.MM.DD HH:mm:ss') + ' ~ ' + moment(row.msmtStDt).format('YYYY.MM.DD HH:mm:ss');
                    return moment(data).format('HH:mm:ss');
                }
            },
            {data: 'gameCd', className: 'text-center col-md-1', defaultContent: "",
                render: (data, display, row: GameRst) => {
                    return I18nService.getInstance().getTranslation(data);
                }
            },
            {data: 'cent', className: 'text-center col-md-1', defaultContent: ""},
            {data: 'scr', className: 'text-center col-md-1', defaultContent: ""},
            {data: 'grd', className: 'text-center col-md-1', defaultContent: ""},
        ],
        rowCallback: (row: Node, data: GameRst, index: number) => {
            $('td', row).unbind('click');
            $('td', row).bind('click', (e) => {
                let actionStr: string = e.target.getAttribute('action');
            });
            return row;
        }
    };


    public search() {
        this.table.draw();
        // console.log(this.where.search);
    }
    dayRender(data, display, row) {
        let iconHtml = "";
        if(data === 1) {
            // iconHtml = "<span class='badge bg-color-grayDark txt-color-white'>"+data+"</span>";
            iconHtml = "<span style='color: #898989; font-size: 4px;'>"+data+"</span>";
        } else if (data >= 2) {
            iconHtml = "<span class='badge bg-color-greenLight txt-color-white'>"+data+"</span>";
            // iconHtml = "<i class='fa fa-circle'></i>"
        }
        // return iconHtml+"("+data+")";

        return iconHtml;
    }


    selectStartDate(data: Date | any | Event) {
        if (data instanceof Event) {
            if (this.validationService.isDateFormat(data.target['value'])) {
                data = moment(data.target['value'], 'YYYY.MM.DD').toDate()
            } else {
                data.target['value'] = '';
                data = null;
            }
        }
        this.startDt = data; //this.cmsCommonService.getMondayOfWeek(data);
    }

    selectEndDate(data: Date | any | Event) {
        if (data instanceof Event) {
            if (this.validationService.isDateFormat(data.target['value'])) {
                data = moment(data.target['value'], 'YYYY.MM.DD').toDate()
            } else {
                data.target['value'] = '';
                data = null;
            }
        }
        let m = moment(data) as Moment;
        this.endDt = m.add(1, 'day').toDate(); //this.cmsCommonService.getSundayOfWeek(data);
    }
}
