package com.clone.chat.code;

public enum MsgCode {

	SUCCESS,
	ERROR_NULL_POINTER_EXCEPTION,
	ERROR_IO_EXCEPTION,
	ERROR_DUPLICATED_ID,
	ERROR_NOSUCHELEMENTEXCEPTION,
	ERROR_AUTH,
	ERROR_BIND,
	ERROR_UNKNOWN,
	ERROR_ENTITY_NOT_FOUND,
	ERROR_INVALID_FRIEND_RELATIONSHIP,
	//..에러 유형에 따라 추가
	
}
