
SET SCHEMA PUBLIC
INSERT INTO T_USER VALUES('admin',		'admin'			, 'Zh6yS0WwtaEG9x03baDoUQ==',    'ROLE_ADMIN')
INSERT INTO T_USER VALUES('other',		'other'			, 'V95Ajybzw4PtbeKGoV/ZcA==',    'ROLE_USER')


INSERT INTO T_ROLE_AUTH VALUES('ROLE_ADMIN', '/board/read','C')
INSERT INTO T_ROLE_AUTH VALUES('ROLE_ADMIN', '/board/read','R')
INSERT INTO T_ROLE_AUTH VALUES('ROLE_ADMIN', '/board/read','U')
INSERT INTO T_ROLE_AUTH VALUES('ROLE_ADMIN', '/board/read','D')
INSERT INTO T_ROLE_AUTH VALUES('ROLE_ADMIN', '/board/write','C')
INSERT INTO T_ROLE_AUTH VALUES('ROLE_ADMIN', '/board/write','R')
INSERT INTO T_ROLE_AUTH VALUES('ROLE_ADMIN', '/board/write','U')
INSERT INTO T_ROLE_AUTH VALUES('ROLE_ADMIN', '/board/write','D')
                                             
INSERT INTO T_ROLE_AUTH VALUES('ROLE_USER',  '/board/read','R')



INSERT INTO T_CODE VALUES('CODE000',   '리턴값',   'CODE000')
INSERT INTO T_CODE VALUES('CODE001',   '성공',    'CODE000')
INSERT INTO T_CODE VALUES('CODE002',   '실패',    'CODE000')
INSERT INTO T_CODE VALUES('CODE003',   '알수없음', 'CODE000')
INSERT INTO T_CODE VALUES('CODE100',   '고객타입', 'CODE100')
INSERT INTO T_CODE VALUES('CODE101',   '슈퍼고객', 'CODE100')
INSERT INTO T_CODE VALUES('CODE102',   '일반고객', 'CODE100')


INSERT INTO T_BOARD (CONTENT, USER_ID, PWD, REGDT)VALUES( '제목1','admin','cpjMc4d06lQZgPY89iSTzQ==', CURRENT_TIMESTAMP)
INSERT INTO T_BOARD (CONTENT, USER_ID, PWD, REGDT)VALUES( '제목2','admin','cpjMc4d06lQZgPY89iSTzQ==', CURRENT_TIMESTAMP)
INSERT INTO T_BOARD (CONTENT, USER_ID, PWD, REGDT)VALUES( '제목3','other','cpjMc4d06lQZgPY89iSTzQ==', CURRENT_TIMESTAMP)
INSERT INTO T_BOARD (CONTENT, USER_ID, PWD, REGDT)VALUES( '제목4','admin','cpjMc4d06lQZgPY89iSTzQ==', CURRENT_TIMESTAMP)
INSERT INTO T_BOARD (CONTENT, USER_ID, PWD, REGDT)VALUES( '제목5','admin','cpjMc4d06lQZgPY89iSTzQ==', CURRENT_TIMESTAMP)
INSERT INTO T_BOARD (CONTENT, USER_ID, PWD, REGDT)VALUES( '제목6','other','cpjMc4d06lQZgPY89iSTzQ==', CURRENT_TIMESTAMP)
INSERT INTO T_BOARD (CONTENT, USER_ID, PWD, REGDT)VALUES( '제목6','other1','cpjMc4d06lQZgPY89iSTzQ==', CURRENT_TIMESTAMP)
